<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>42b2dacc-28d4-4ea1-9518-0eb31361d625</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="13.1.0-preview.1.25616.3" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TempooHub.Api\TempooHub.Api.csproj" />
  </ItemGroup>

</Project>
